// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:1a54933b-7f32-4859-94c3-a25f9bd07ddc",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_KH2Xxgr03",
    "aws_user_pools_web_client_id": "53mle2rg1rub8qfmob1v9r64sm",
    "aws_content_delivery_bucket": "amplify-dashboard-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://amplify-dashboard-dev.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
